#!/usr/bin/env python3

import sys
from subprocess import check_output, check_call, CalledProcessError

# pipe command to git executable
try:
    check_call(['git'] + sys.argv[1:])
except CalledProcessError:
    exit(1)

# if commit was made sign it with ksi
if sys.argv[1] == 'commit':

    # retrieve SHA1 commit hash
    commit_checksum = check_output(["git", "show"])[7:47]
    